---
version: "3"

services:
  y-x-ui-2.3:
    image: ghcr.io/yasinabbasiiii/y-x-ui-2.3:latest
    container_name: y-x-ui-2.3
    hostname: yourhostname
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
